# Generated by Django 3.2.9 on 2021-11-18 01:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_features_watch', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('movie_features_click', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('movie_features_like', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('movie_features_dislike', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_features_watch', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('user_features_click', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('user_features_like', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
                ('user_features_dislike', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10)),
            ],
        ),
    ]
