# Generated by Django 3.2.9 on 2021-11-29 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_ms', '0006_auto_20211122_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_features_click',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_features_dislike',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_features_like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_features_watch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_features_click',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_features_dislike',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_features_like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_features_watch',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=30),
        ),
    ]
