# Generated by Django 3.2.9 on 2021-12-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_ms', '0007_auto_20211129_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_features_click',
            new_name='profile_features_click',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_features_dislike',
            new_name='profile_features_dislike',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_features_like',
            new_name='profile_features_like',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_features_watch',
            new_name='profile_features_watch',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='profile_id',
        ),
    ]
