# Generated by Django 3.2.9 on 2021-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_ms', '0009_auto_20211204_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
