version: "3.4"
   
services:
  recommendation_db:
    image: postgres:14.1
    container_name: crowstream_recommendation_db
    volumes:
      - ./init_recommendation_db.sql:/docker-entrypoint-initdb.d/init_recommendation_db.sql
    environment:
      - POSTGRES_DB=${RECOMMENDATION_DB_DATABASE}
      - POSTGRES_USER=${RECOMMENDATION_DB_USER}
      - POSTGRES_PASSWORD=${RECOMMENDATION_DB_PASSWORD}
    ports:
      - "5432:5432"
  recommendation_ms:
    image: crowstream2021/crowstream_recommendation_ms
    container_name: crowstream_recommendation_ms
    command: python ./recommendation/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/recommendation/manage.py run server 0.0.0.:8000
    ports:
      - "8000:8000"
    depends_on:
      - recommendation_db


